### ISSUE TITLE
Failed loading Op multibox_target of type _contrib_MultiBoxTarget: [06:17:43] jni/../mxnet_predict-all.cc:26565:

### ISSUE THREAD

**Issue by sahibzadaadil** [sunkwei/SSD_Demo_Android#5]
![issue](https://user-images.githubusercontent.com/39368653/52446796-f85e4980-2b69-11e9-9135-cfb26afd716c.JPG)
Hello, I'm facing this issue while running it on Android studio with mobilenet pretrained model.
Can you please tell me about the Android operating system version or any other special requirement to run it on android?

**Comment by sunkwei** [comment]
"failed loading Op multibox_target of type _contrib_MultiBoxTarget" is mean the runtime cannot find the _contrib_MultiBoxTarget oper. you should add:
#include "src/operator/contrib/multibox_detection.cc"
#include "src/operator/contrib/multibox_prior.cc"

**Comment by sahibzadaadil** [comment]
![error 2](https://user-images.githubusercontent.com/39368653/52521229-e5a15d00-2cae-11e9-9d25-f24c15596e2e.JPG)
Thanks for response. As a beginner I'm not getting where the issue is? 
Can you please tell me the steps to run the code in android studio, maybe due to some chinese characters I'm missing some important things. I just clone the code from this repository and downloaded the pretrained mobile net mobilenet-ssd-512-0001.params & mobilenet-ssd-512-symbol.json and renamed it to ssd-mobile-512-0000.params & ssd-mobile-512-symbol.json repectively. 
When I run it on the app crashes with the following error 

 Caused by: org.dmlc.mxnet.MxnetException: Failed loading Op multibox_target of type _contrib_MultiBoxTarget: [20:44:27] jni/../mxnet_predict-all.cc:26565: Check failed: op != nullptr Operator _contrib_MultiBoxTarget is not registered
        at org.dmlc.mxnet.Predictor.createPredictor(Native Method)
        at org.dmlc.mxnet.Predictor.<init>(Predictor.java:65)
        at cc.hetinsow.sunkw.ssd_demo.MainActivity.init_predictor(MainActivity.java:297)
        at cc.hetinsow.sunkw.ssd_demo.MainActivity.onCreate(MainActivity.java:67)

**Comment by sunkwei** [comment]
refer https://github.com/apache/incubator-mxnet/tree/master/amalgamation, and https://stackoverflow.com/questions/42914167/cannot-resolve-corresponding-jni-function-android-studio . im newbie of AS, just try more :)

**Comment by SahibzadaAdil** [comment]
Hi, it seems like the problem is with the operators.  Can you please share your libmxnet_predict.so file for SSD and mobilnet?
E-ID: adilshah275@gmail.com

**Comment by sunkwei** [comment]
the .so files is in https://github.com/sunkwei/SSD_Demo_Android/tree/master/app/src/main/jniLibs
