### ISSUE TITLE
error: call of overloaded 'NodeEntry(<brace-enclosed initializer list>)' is ambiguous

### ISSUE THREAD

**Issue by kwanking** [sunkwei/SSD_Demo_Android#7]
copy your files to incubator-mxnet-1.4.0/amalgamation and make. However there are some errors. I have tried   mxnet 1.4.0,   ther version of ndk  is 19, 16b,12b. Would you like tell me how do I do, or tell me your version of ndk? 

/home/kk/incubator-mxnet-1.4.0/amalgamation/../3rdparty/tvm/nnvm/include/nnvm/node.h:52:8: note: nnvm::NodeEntry::NodeEntry(nnvm::NodeEntry&&)
In file included from ../include/mxnet/./op_attr_types.h:36:0,
                 from ../include/mxnet/operator.h:40,
                 from ../src/c_api/c_api_ndarray.cc:28,
                 from jni/../mxnet_predict-all.cc:34,
                 from jni/predictor.cc:23:
../include/mxnet/././ndarray.h: In constructor 'mxnet::NDArray::NDArray(const mxnet::TBlob&, int)':
../include/mxnet/././ndarray.h:128:31: error: call of overloaded 'NodeEntry(<brace-enclosed initializer list>)' is ambiguous
         entry_({nullptr, 0, 0}) {
                               ^

**Comment by shiyuangogogo** [comment]
hi @kwanking I met the same issue as you. my MXNET amalgamation compile log  in below. Had you fix the issue？Appreciate for your any help.  @sunkwei 朋友，可以帮看一下吗

...
...
...
/opt/android-toolchain/bin/aarch64-linux-android-clang++ -std=c++11 -Wno-unknown-pragmas -Wall -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_SSE=0 -DDISABLE_OPENMP=1 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DDMLC_LOG_STACK_TRACE=0 -DMSHADOW_FORCE_STREAM -DMXNET_USE_OPENCV=0 -DMXNET_PREDICT_ONLY=1 -DMSHADOW_USE_F16C=0 -I/opt/openblas-android -I/opt/openblas-android/include -mhard-float -D_NDK_MATH_NO_SOFTFP=1 -O3 -fPIC -o jni_libmxnet_predict.o -c jni/predictor.cc
clang50++: warning: argument unused during compilation: '-mhard-float' [-Wunused-command-line-argument]
In file included from jni/predictor.cc:23:
jni/../mxnet_predict-all.cc:416:1: warning: '/*' within block comment [-Wcomment]
/*!
^
jni/../mxnet_predict-all.cc:10970:9: warning: 'MSHADOW_FORCE_STREAM' macro redefined [-Wmacro-redefined]
#define MSHADOW_FORCE_STREAM
        ^
<command line>:10:9: note: previous definition is here
#define MSHADOW_FORCE_STREAM 1
        ^
In file included from jni/predictor.cc:23:
jni/../mxnet_predict-all.cc:36738:9: error: call to constructor of 'nnvm::NodeEntry' is ambiguous
        entry_({nullptr, 0, 0}) {
        ^      ~~~~~~~~~~~~~~~
jni/../mxnet_predict-all.cc:24332:8: note: candidate is the implicit move constructor
struct NodeEntry {
       ^
jni/../mxnet_predict-all.cc:24332:8: note: candidate is the implicit copy constructor
jni/../mxnet_predict-all.cc:24339:12: note: candidate constructor
  explicit NodeEntry(NodePtr node):
           ^
jni/../mxnet_predict-all.cc:36768:9: error: call to constructor of 'nnvm::NodeEntry' is ambiguous
        entry_({nullptr, 0, 0}) {
        ^      ~~~~~~~~~~~~~~~
jni/../mxnet_predict-all.cc:24332:8: note: candidate is the implicit move constructor
struct NodeEntry {
       ^
jni/../mxnet_predict-all.cc:24332:8: note: candidate is the implicit copy constructor
jni/../mxnet_predict-all.cc:24339:12: note: candidate constructor
  explicit NodeEntry(NodePtr node):
           ^
jni/../mxnet_predict-all.cc:36787:9: error: call to constructor of 'nnvm::NodeEntry' is ambiguous
        entry_({nullptr, 0, 0}) {
        ^      ~~~~~~~~~~~~~~~
jni/../mxnet_predict-all.cc:24332:8: note: candidate is the implicit move constructor
struct NodeEntry {
       ^
jni/../mxnet_predict-all.cc:24332:8: note: candidate is the implicit copy constructor
jni/../mxnet_predict-all.cc:24339:12: note: candidate constructor
  explicit NodeEntry(NodePtr node):
           ^
jni/../mxnet_predict-all.cc:36793:56: error: call to constructor of 'nnvm::NodeEntry' is ambiguous
        dtype_(dtype), storage_type_(kDefaultStorage), entry_({nullptr, 0, 0}) {
                                                       ^      ~~~~~~~~~~~~~~~
jni/../mxnet_predict-all.cc:24332:8: note: candidate is the implicit move constructor
struct NodeEntry {
       ^
jni/../mxnet_predict-all.cc:24332:8: note: candidate is the implicit copy constructor
jni/../mxnet_predict-all.cc:24339:12: note: candidate constructor
  explicit NodeEntry(NodePtr node):
           ^
jni/../mxnet_predict-all.cc:36809:56: error: call to constructor of 'nnvm::NodeEntry' is ambiguous
        dtype_(data.type_flag_), storage_type_(stype), entry_({nullptr, 0, 0}) {
                                                       ^      ~~~~~~~~~~~~~~~
jni/../mxnet_predict-all.cc:24332:8: note: candidate is the implicit move constructor
struct NodeEntry {
       ^
jni/../mxnet_predict-all.cc:24332:8: note: candidate is the implicit copy constructor
jni/../mxnet_predict-all.cc:24339:12: note: candidate constructor
  explicit NodeEntry(NodePtr node):
           ^
jni/../mxnet_predict-all.cc:56335:40: error: call to constructor of 'nnvm::NodeEntry' is ambiguous
  dtype_(dtype), storage_type_(stype), entry_({nullptr, 0, 0}) {
                                       ^      ~~~~~~~~~~~~~~~
jni/../mxnet_predict-all.cc:24332:8: note: candidate is the implicit move constructor
struct NodeEntry {
       ^
jni/../mxnet_predict-all.cc:24332:8: note: candidate is the implicit copy constructor
jni/../mxnet_predict-all.cc:24339:12: note: candidate constructor
  explicit NodeEntry(NodePtr node):
           ^
jni/../mxnet_predict-all.cc:69136:8: warning: 'mxnet::profiler::ProfileOperator::start' hides overloaded virtual function [-Woverloaded-virtual]
  void start(mxnet::Context::DeviceType dev_type, uint32_t dev_id) {
...
...
...

**Comment by kwanking** [comment]
@moliqian I build .so and .a with mxnet/ci.

**Comment by shiyuangogogo** [comment]
@kwanking i know "mxnet", but what does "mxnet/ci" means?
